---
tenants:
  # Tenant A VRFs / VLANs
  - name: Tenant_A
    mac_vrf_vni_base: 10000
    l2vlans:
      - id: 100
        name: Tenant_A_OP_Zone_1
        tags:
          - opzone_pod1
      - id: 200
        name: Tenant_A_OP_Zone_2
        tags:
          - opzone_pod1
    evpn_l2_multicast:
      enabled: true
      underlay_l2_multicast_group_ipv4_pool: 232.1.0.0/20
      underlay_l2_multicast_group_ipv4_pool_offset: 1
